[package]
name = "CoreAPI"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
futures-util = "0.3"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
