#!/usr/bin/env bash

# GDPR usage simulation (MAIR-497, mairie360/CICD tests/gdpr/simulation). Test stack only: needs
# GDPR_SIMULATION=test-stack (the CICD action exports it), the engine refuses anything else.
#
#   1. docker-compose-gdpr-simulation.yml: the `gdpr-simulation` runner plays gdpr-simulation.yaml
#      with fictitious personas (journey + erase steps) and writes gdpr-simulation/personas.json;
#   2. the sessions and connection logs of the run are back-dated past their retention, then the
#      purge runs (fn_apply_retention_policies);
#   3. the database checks generated by the engine from the inventory (Devops/Database
#      gdpr/inventory.yaml at GDPR_INVENTORY_REF, `main` by default) and the schema are run:
#      erased personas' values, rows past retention, a sample of the free-text columns;
#   4. the logs of every container are saved, then the stack is removed.
# The CICD action then runs analyze.mjs on gdpr-simulation/ (deterministic checks + AI review).
# Exit 0: everything played; 1: a step failed; 2: missing input.
#
# The API under test is IMAGE_REF (CI: the image promoted to staging); empty, it is built from
# development.Dockerfile as core-api:local. Running every operation with k6 (load-test.js) is a
# follow-up: its load scenarios are too heavy for this stack.

COMPOSE_FILE="docker-compose-gdpr-simulation.yml"
RUN_DIR="gdpr-simulation"
DB="mairie_360_database"
INVENTORY_REF="${GDPR_INVENTORY_REF:-main}"

if [ "${GDPR_SIMULATION:-}" != "test-stack" ]; then
    echo "GDPR_SIMULATION=test-stack is not set: the simulation only runs on a test stack."
    exit 2
fi
export GDPR_SIMULATION

if [ -z "${IMAGE_REF:-}" ]; then
    echo "==> [0/5] IMAGE_REF is empty: building core-api:local from development.Dockerfile..."
    IMAGE_REF="core-api:local"
    docker build -f development.Dockerfile -t "$IMAGE_REF" . || exit 1
fi
export IMAGE_REF
echo "==> API image under test: $IMAGE_REF"

# Random JWT_SECRET for this run and the admin JWT signed with it (MAIR-428).
# shellcheck source=stack_secrets.sh
source ./stack_secrets.sh || exit 1

CICD_DIR="cicd-repo"
if [ ! -f "$CICD_DIR/tests/gdpr/simulation/simulate.mjs" ]; then
    CICD_VERSION="${CICD_VERSION:-$(sed -n 's/^[[:space:]]*cicd_version:[[:space:]]*\([^[:space:]#]*\).*/\1/p' .github/workflows/cicd.yml | head -n 1)}"
    echo "==> Fetching mairie360/CICD $CICD_VERSION into $CICD_DIR/..."
    rm -rf "$CICD_DIR"
    git clone --quiet --depth 1 --branch "$CICD_VERSION" https://github.com/mairie360/CICD "$CICD_DIR" || exit 1
fi

rm -rf "$RUN_DIR" && mkdir -p "$RUN_DIR/db"
curl -fsSL "https://raw.githubusercontent.com/mairie360/Database/$INVENTORY_REF/gdpr/inventory.yaml" -o "$RUN_DIR/inventory.yaml" \
    || { echo "No gdpr/inventory.yaml at mairie360/Database@$INVENTORY_REF (GDPR_INVENTORY_REF)."; exit 2; }

# The stack is always removed, even when the script is interrupted (CI bounds it with `timeout`).
trap 'docker compose -f "$COMPOSE_FILE" down -v >/dev/null 2>&1' EXIT
psql_stack() {
    docker compose -f "$COMPOSE_FILE" exec -T postgres psql -U postgres -d "$DB" -v ON_ERROR_STOP=1 -At "$@"
}

echo "==> [1/5] Starting the stack and the personas' journeys..."
docker compose -f "$COMPOSE_FILE" up -d
docker compose -f "$COMPOSE_FILE" wait gdpr-simulation
RUNNER_EXIT=$?
docker compose -f "$COMPOSE_FILE" logs --no-color --tail 60 gdpr-simulation

echo "==> [2/5] Back-dating the rows of the run past their retention, then the purge..."
psql_stack <<'SQL'
UPDATE sessions SET created_at = created_at - interval '7 months', expires_at = expires_at - interval '7 months'
 WHERE created_at > now() - interval '1 day';
UPDATE connection_logs SET timestamp = timestamp - interval '13 months'
 WHERE timestamp > now() - interval '1 day';
SELECT * FROM fn_apply_retention_policies();
SQL

echo "==> [3/5] Database checks..."
psql_stack -f - < "$CICD_DIR/tests/gdpr/schema.sql" > "$RUN_DIR/schema.json" || exit 1
docker run --rm -u "$(id -u):$(id -g)" -e HOME=/tmp -v "$PWD/$CICD_DIR/tests/gdpr:/engine:ro" -v "$PWD/$RUN_DIR:/run" node:24-bookworm-slim sh -c \
    'mkdir -p /tmp/engine && tar -C /engine --exclude=./node_modules -cf - . | tar -C /tmp/engine -xf - && cd /tmp/engine && npm ci --omit=dev --no-audit --no-fund --loglevel=error && node simulation/sql.mjs /run/inventory.yaml /run/schema.json /run' \
    || exit 1
for query in erasure retention content; do
    psql_stack -f - < "$RUN_DIR/db/$query.sql" > "$RUN_DIR/db/$query.sql.json" || exit 1
done

echo "==> [4/5] Saving the logs of every container..."
docker compose -f "$COMPOSE_FILE" logs --no-color > "$RUN_DIR/containers.log"

echo "==> [5/5] Removing the stack..."
docker compose -f "$COMPOSE_FILE" down -v

echo "Runner exit code: $RUNNER_EXIT"
[ "$RUNNER_EXIT" -eq 0 ] || exit 1
exit 0
