events {
    worker_connections 1024;
}

http {
    # 1. Utiliser le DNS interne de Docker (obligatoire pour les variables)
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        server_name core.development.mairie360.fr;

        location / {
            # 2. On définit l'hôte dans une variable. 
            # Nginx ne vérifiera l'existence de "core" qu'au moment de l'appel.
            set $target http://core:3000;

            proxy_pass $target;
            
            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}