[package]
name = "api_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
once_cell = "1.21.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
