name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check Dependencies with Cargo
        uses: actions-rs/cargo@v1
        with:
          command: check

  lint:
    name: Check lint
    runs-on: ubuntu-latest
    needs: check_dependencies

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run lint_check
        uses: actions-rs/cargo@v1
        with:
          command: lint_check

      - name: Run lint_fix
        uses: actions-rs/cargo@v1
        with:
          command: lint_fix


  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust Project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test

